language: python
python:
    - "2.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure.
sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORM_CI_SRC=examples/BasicExample
    - PLATFORM_CI_SRC=examples/AdvancedExample

install:
    - pip install -U platformio

script:
    - platformio ci --lib="." --board=uno --board=megaatmega2560 --board=micro --board=leonardo

notifications:
    email:
        on_success: change
        on_failure: change
